version: '3'
services:
  nester-uno:
    build: .
    hostname: nester
    ports:
      - "127.0.0.1:5000:5000"

  harvester-egy:
    build: ./harvester
    hostname: Harvester-egy
    network_mode: host
    
  harvester-dos:
    build: ./harvester
    hostname: Harvester-dos
    network_mode: host

  harvester-three:
    build: ./harvester
    hostname: Harvester-three
    network_mode: host

  harvester-vier:
    build: ./harvester
    hostname: Harvester-vier
    network_mode: host

  harvester-cinq:
    build: ./harvester
    hostname: Harvester-cinq
    network_mode: host
  
  harvester-sechs:
    build: ./harvester
    hostname: Harvester-sechs
    network_mode: host
  
  harvester-sieben:
    build: ./harvester
    hostname: Harvester-sieben
    network_mode: host 
  
  harvester-huit:
    build: ./harvester
    hostname: Harvester-huit
    network_mode: host 
  
  harvester-neuf:
    build: ./harvester
    hostname: Harvester-neuf
    network_mode: host 
  
  harvester-ten:
    build: ./harvester
    hostname: Harvester-ten
    network_mode: host 
  
  harvester-onze:
    build: ./harvester
    hostname: Harvester-onze
    network_mode: host 

  harvester-treize:
    build: ./harvester
    hostname: Harvester-treize
    network_mode: host 
  
  harvester-quatorze:
    build: ./harvester
    hostname: Harvester-quatorze
    network_mode: host 
  

