version: '3'
services:
  nester-uno:
    build: .
    hostname: nester
    network_mode: host 

  harvester-egy:
    build: ./harvester
    hostname: Harvester-egy
    network_mode: host
    
  harvester-dos:
    build: ./harvester
    hostname: Harvester-dos
    network_mode: host

  harvester-three:
    build: ./harvester
    hostname: Harvester-three
    network_mode: host

  harvester-vier:
    build: ./harvester
    hostname: Harvester-vier
    network_mode: host

  harvester-cinq:
    build: ./harvester
    hostname: Harvester-cinq
    network_mode: host