version: '3'
services:
  client-egy:
    build: ./client
    hostname: Harvester-egy

  client-dos:
    build: ./client
    hostname: Harvester-dos

  client-three:
    build: ./client
    hostname: Harvester-three

  client-vier:
    build: ./client
    hostname: Harvester-vier

  client-cinq:
    build: ./client
    hostname: Harvester-cinq
