version: '3'
services:
  nester-uno:
    build: .
    hostname: nester
    ports:
      - "127.0.0.1:5000:5000"

  client-egy:
    build: ./harvester
    hostname: client-egy
    network_mode: host
    
  client-dos:
    build: ./harvester
    hostname: client-dos
    network_mode: host

  client-three:
    build: ./harvester
    hostname: client-three
    network_mode: host

  client-vier:
    build: ./harvester
    hostname: client-vier
    network_mode: host

  client-cinq:
    build: ./harvester
    hostname: client-cinq
    network_mode: host
  
  client-sechs:
    build: ./harvester
    hostname: client-sechs
    network_mode: host
  

